import { CertificateElement, CertificateCategory } from '@/lib/types';

export interface CertificatePreset {
  id: string;
  name: string;
  description: string;
  category: CertificateCategory;
  width: number;
  height: number;
  backgroundColor: string;
  backgroundImage?: string;
  elements: CertificateElement[];
}

export const CERTIFICATE_PRESETS: CertificatePreset[] = [
  {
    id: 'blank',
    name: 'Kanvas Kosong (Blank)',
    description: 'Bermula dari asas dengan susun atur teks standard.',
    category: 'other',
    width: 1123,
    height: 794,
    backgroundColor: '#ffffff',
    elements: [
      {
        id: 'title',
        type: 'text',
        x: 561,
        y: 120,
        width: 500,
        height: 60,
        content: 'SIJIL PENGHARGAAN',
        fontSize: 36,
        fontFamily: 'Playfair Display, serif',
        fontWeight: 'bold',
        color: '#0f172a',
        textAlign: 'center',
      },
      {
        id: 'subtitle',
        type: 'text',
        x: 561,
        y: 190,
        width: 400,
        height: 30,
        content: 'Dengan ini diperakui bahawa',
        fontSize: 16,
        fontFamily: 'sans-serif',
        color: '#64748b',
        textAlign: 'center',
      },
      {
        id: 'name-placeholder',
        type: 'placeholder',
        x: 561,
        y: 270,
        width: 600,
        height: 70,
        placeholderType: 'name',
        fontSize: 46,
        fontFamily: 'Great Vibes, cursive',
        color: '#0f172a',
        textAlign: 'center',
      },
      {
        id: 'program-label',
        type: 'text',
        x: 561,
        y: 360,
        width: 400,
        height: 30,
        content: 'telah berjaya menyertai dan menyempurnakan',
        fontSize: 16,
        fontFamily: 'sans-serif',
        color: '#64748b',
        textAlign: 'center',
      },
      {
        id: 'program-placeholder',
        type: 'placeholder',
        x: 561,
        y: 420,
        width: 650,
        height: 50,
        placeholderType: 'program',
        fontSize: 26,
        fontFamily: 'Playfair Display, serif',
        fontWeight: 'bold',
        color: '#0f172a',
        textAlign: 'center',
      },
      {
        id: 'date-placeholder',
        type: 'placeholder',
        x: 250,
        y: 650,
        width: 220,
        height: 30,
        placeholderType: 'date',
        fontSize: 14,
        fontFamily: 'sans-serif',
        color: '#475569',
        textAlign: 'center',
      },
      {
        id: 'sig-line-1',
        type: 'shape',
        shapeType: 'line',
        x: 873,
        y: 630,
        width: 200,
        height: 2,
        fill: '#94a3b8',
      },
      {
        id: 'sig-name-1',
        type: 'text',
        x: 873,
        y: 660,
        width: 220,
        height: 30,
        content: 'PENGARAH PROGRAM',
        fontSize: 14,
        fontFamily: 'sans-serif',
        fontWeight: 'bold',
        color: '#0f172a',
        textAlign: 'center',
      },
    ],
  },
  {
    id: 'royal-gold',
    name: 'Klasik Diraja (Royal Gold)',
    description: 'Reka bentuk formal mewah dengan bingkai emas berganda dan kaligrafi.',
    category: 'event',
    width: 1123,
    height: 794,
    backgroundColor: '#0f172a',
    elements: [
      {
        id: 'outer-border',
        type: 'shape',
        shapeType: 'rectangle',
        x: 561,
        y: 397,
        width: 1043,
        height: 714,
        fill: 'transparent',
        stroke: '#f59e0b',
        strokeWidth: 4,
      },
      {
        id: 'inner-border',
        type: 'shape',
        shapeType: 'rectangle',
        x: 561,
        y: 397,
        width: 1015,
        height: 686,
        fill: 'transparent',
        stroke: '#d97706',
        strokeWidth: 1,
      },
      {
        id: 'royal-icon',
        type: 'icon',
        iconName: 'Award',
        x: 561,
        y: 80,
        width: 44,
        height: 44,
        stroke: '#fbbf24',
        strokeWidth: 2,
      },
      {
        id: 'royal-title',
        type: 'text',
        x: 561,
        y: 140,
        width: 600,
        height: 50,
        content: 'SIJIL PENGHARGAAN DIRAJA',
        fontSize: 34,
        fontFamily: 'Cinzel, serif',
        fontWeight: 'bold',
        color: '#fbbf24',
        textAlign: 'center',
        letterSpacing: 2,
      },
      {
        id: 'royal-subtitle',
        type: 'text',
        x: 561,
        y: 195,
        width: 450,
        height: 25,
        content: 'DENGAN INI DIPERAKUI BAHAWA',
        fontSize: 13,
        fontFamily: 'Cinzel, serif',
        color: '#cbd5e1',
        textAlign: 'center',
        letterSpacing: 3,
      },
      {
        id: 'name-placeholder',
        type: 'placeholder',
        x: 561,
        y: 275,
        width: 750,
        height: 75,
        placeholderType: 'name',
        fontSize: 50,
        fontFamily: 'Great Vibes, cursive',
        color: '#fef08a',
        textAlign: 'center',
      },
      {
        id: 'name-divider',
        type: 'shape',
        shapeType: 'line',
        x: 561,
        y: 335,
        width: 450,
        height: 2,
        fill: '#b45309',
      },
      {
        id: 'program-intro',
        type: 'text',
        x: 561,
        y: 375,
        width: 500,
        height: 25,
        content: 'telah menunjukkan komitmen & pencapaian cemerlang dalam',
        fontSize: 15,
        fontFamily: 'serif',
        fontStyle: 'italic',
        color: '#94a3b8',
        textAlign: 'center',
      },
      {
        id: 'program-placeholder',
        type: 'placeholder',
        x: 561,
        y: 435,
        width: 700,
        height: 45,
        placeholderType: 'program',
        fontSize: 26,
        fontFamily: 'Cinzel, serif',
        fontWeight: 'bold',
        color: '#ffffff',
        textAlign: 'center',
      },
      // Dual Signatories
      {
        id: 'sig-1-line',
        type: 'shape',
        shapeType: 'line',
        x: 270,
        y: 630,
        width: 220,
        height: 2,
        fill: '#fbbf24',
      },
      {
        id: 'sig-1-name',
        type: 'text',
        x: 270,
        y: 655,
        width: 240,
        height: 25,
        content: 'PENASIHAT PROGRAM',
        fontSize: 13,
        fontFamily: 'Cinzel, serif',
        fontWeight: 'bold',
        color: '#fbbf24',
        textAlign: 'center',
      },
      {
        id: 'sig-1-role',
        type: 'text',
        x: 270,
        y: 680,
        width: 240,
        height: 25,
        content: 'Dato\' Sri Dr. Pengerusi',
        fontSize: 13,
        fontFamily: 'sans-serif',
        color: '#cbd5e1',
        textAlign: 'center',
      },
      {
        id: 'qr-code',
        type: 'qr',
        x: 561,
        y: 645,
        width: 75,
        height: 75,
        qrData: '{VERIFY_URL}',
        color: '#0f172a',
      },
      {
        id: 'sig-2-line',
        type: 'shape',
        shapeType: 'line',
        x: 853,
        y: 630,
        width: 220,
        height: 2,
        fill: '#fbbf24',
      },
      {
        id: 'sig-2-name',
        type: 'text',
        x: 853,
        y: 655,
        width: 240,
        height: 25,
        content: 'PENGARAH EKSEKUTIF',
        fontSize: 13,
        fontFamily: 'Cinzel, serif',
        fontWeight: 'bold',
        color: '#fbbf24',
        textAlign: 'center',
      },
      {
        id: 'sig-2-role',
        type: 'text',
        x: 853,
        y: 680,
        width: 240,
        height: 25,
        content: 'Prof. Madya Dr. Pengarah',
        fontSize: 13,
        fontFamily: 'sans-serif',
        color: '#cbd5e1',
        textAlign: 'center',
      },
      {
        id: 'date-placeholder',
        type: 'placeholder',
        x: 561,
        y: 710,
        width: 200,
        height: 25,
        placeholderType: 'date',
        fontSize: 12,
        fontFamily: 'sans-serif',
        color: '#94a3b8',
        textAlign: 'center',
      },
    ],
  },
  {
    id: 'corporate-blue',
    name: 'Korporat Moden (Corporate Blue)',
    description: 'Gaya profesional korporat dengan aksen warna biru laut & garis geometri.',
    category: 'corporate',
    width: 1123,
    height: 794,
    backgroundColor: '#ffffff',
    elements: [
      {
        id: 'top-bar',
        type: 'shape',
        shapeType: 'rectangle',
        x: 561,
        y: 12,
        width: 1123,
        height: 24,
        fill: '#1e3a8a',
      },
      {
        id: 'top-accent',
        type: 'shape',
        shapeType: 'rectangle',
        x: 561,
        y: 28,
        width: 1123,
        height: 6,
        fill: '#3b82f6',
      },
      {
        id: 'corp-icon',
        type: 'icon',
        iconName: 'Shield',
        x: 561,
        y: 90,
        width: 48,
        height: 48,
        stroke: '#1e3a8a',
        strokeWidth: 2,
      },
      {
        id: 'corp-title',
        type: 'text',
        x: 561,
        y: 155,
        width: 650,
        height: 45,
        content: 'CERTIFICATE OF ACHIEVEMENT',
        fontSize: 32,
        fontFamily: 'Montserrat, sans-serif',
        fontWeight: 'bold',
        color: '#1e3a8a',
        textAlign: 'center',
        letterSpacing: 3,
      },
      {
        id: 'corp-subtitle',
        type: 'text',
        x: 561,
        y: 205,
        width: 400,
        height: 25,
        content: 'PROUDLY PRESENTED TO',
        fontSize: 13,
        fontFamily: 'Montserrat, sans-serif',
        color: '#64748b',
        textAlign: 'center',
        letterSpacing: 2,
      },
      {
        id: 'name-placeholder',
        type: 'placeholder',
        x: 561,
        y: 275,
        width: 750,
        height: 65,
        placeholderType: 'name',
        fontSize: 44,
        fontFamily: 'Montserrat, sans-serif',
        fontWeight: 'bold',
        color: '#0f172a',
        textAlign: 'center',
      },
      {
        id: 'corp-desc',
        type: 'text',
        x: 561,
        y: 350,
        width: 600,
        height: 30,
        content: 'in recognition of outstanding professional performance in',
        fontSize: 16,
        fontFamily: 'sans-serif',
        color: '#475569',
        textAlign: 'center',
      },
      {
        id: 'program-placeholder',
        type: 'placeholder',
        x: 561,
        y: 410,
        width: 700,
        height: 45,
        placeholderType: 'program',
        fontSize: 26,
        fontFamily: 'Montserrat, sans-serif',
        fontWeight: 'bold',
        color: '#1d4ed8',
        textAlign: 'center',
      },
      {
        id: 'bottom-accent',
        type: 'shape',
        shapeType: 'rectangle',
        x: 561,
        y: 770,
        width: 1123,
        height: 6,
        fill: '#3b82f6',
      },
      {
        id: 'bottom-bar',
        type: 'shape',
        shapeType: 'rectangle',
        x: 561,
        y: 785,
        width: 1123,
        height: 18,
        fill: '#1e3a8a',
      },
      {
        id: 'date-label',
        type: 'text',
        x: 230,
        y: 590,
        width: 200,
        height: 25,
        content: 'TARIKH PENGELUARAN',
        fontSize: 12,
        fontFamily: 'sans-serif',
        fontWeight: 'bold',
        color: '#64748b',
        textAlign: 'center',
      },
      {
        id: 'date-placeholder',
        type: 'placeholder',
        x: 230,
        y: 620,
        width: 200,
        height: 25,
        placeholderType: 'date',
        fontSize: 14,
        fontFamily: 'sans-serif',
        color: '#0f172a',
        textAlign: 'center',
      },
      {
        id: 'qr-code',
        type: 'qr',
        x: 561,
        y: 615,
        width: 80,
        height: 80,
        qrData: '{VERIFY_URL}',
        color: '#1e3a8a',
      },
      {
        id: 'sig-line',
        type: 'shape',
        shapeType: 'line',
        x: 893,
        y: 610,
        width: 220,
        height: 2,
        fill: '#94a3b8',
      },
      {
        id: 'sig-title',
        type: 'text',
        x: 893,
        y: 635,
        width: 240,
        height: 25,
        content: 'MANAGING DIRECTOR',
        fontSize: 13,
        fontFamily: 'Montserrat, sans-serif',
        fontWeight: 'bold',
        color: '#0f172a',
        textAlign: 'center',
      },
      {
        id: 'serial-placeholder',
        type: 'placeholder',
        x: 561,
        y: 685,
        width: 240,
        height: 20,
        placeholderType: 'serial',
        fontSize: 11,
        fontFamily: 'monospace',
        color: '#94a3b8',
        textAlign: 'center',
      },
    ],
  },
  {
    id: 'academic-classic',
    name: 'Akademik & Sekolah (Academic Classic)',
    description: 'Sijil institusi pendidikan & akademik dengan lambang kecemerlangan.',
    category: 'school',
    width: 1123,
    height: 794,
    backgroundColor: '#fffdfa',
    elements: [
      {
        id: 'frame-outer',
        type: 'shape',
        shapeType: 'rectangle',
        x: 561,
        y: 397,
        width: 1040,
        height: 710,
        fill: 'transparent',
        stroke: '#78350f',
        strokeWidth: 3,
      },
      {
        id: 'frame-inner',
        type: 'shape',
        shapeType: 'rectangle',
        x: 561,
        y: 397,
        width: 1020,
        height: 690,
        fill: 'transparent',
        stroke: '#b45309',
        strokeWidth: 1,
      },
      {
        id: 'icon-academic',
        type: 'icon',
        iconName: 'Medal',
        x: 561,
        y: 85,
        width: 46,
        height: 46,
        stroke: '#b45309',
        strokeWidth: 2,
      },
      {
        id: 'school-name',
        type: 'text',
        x: 561,
        y: 140,
        width: 600,
        height: 30,
        content: 'KEMENTERIAN PENDIDIKAN MALAYSIA',
        fontSize: 14,
        fontFamily: 'sans-serif',
        fontWeight: 'bold',
        color: '#78350f',
        textAlign: 'center',
        letterSpacing: 2,
      },
      {
        id: 'academic-title',
        type: 'text',
        x: 561,
        y: 185,
        width: 700,
        height: 45,
        content: 'SIJIL PENCAPAIAN CEMERLANG',
        fontSize: 34,
        fontFamily: 'Playfair Display, serif',
        fontWeight: 'bold',
        color: '#451a03',
        textAlign: 'center',
      },
      {
        id: 'academic-certifies',
        type: 'text',
        x: 561,
        y: 235,
        width: 500,
        height: 25,
        content: 'Dengan sukacitanya mengesahkan bahawa',
        fontSize: 15,
        fontFamily: 'serif',
        fontStyle: 'italic',
        color: '#78350f',
        textAlign: 'center',
      },
      {
        id: 'name-placeholder',
        type: 'placeholder',
        x: 561,
        y: 300,
        width: 750,
        height: 65,
        placeholderType: 'name',
        fontSize: 44,
        fontFamily: 'Playfair Display, serif',
        fontWeight: 'bold',
        color: '#78350f',
        textAlign: 'center',
      },
      {
        id: 'ic-placeholder',
        type: 'placeholder',
        x: 561,
        y: 350,
        width: 300,
        height: 25,
        placeholderType: 'ic',
        fontSize: 15,
        fontFamily: 'sans-serif',
        color: '#92400e',
        textAlign: 'center',
      },
      {
        id: 'program-intro',
        type: 'text',
        x: 561,
        y: 395,
        width: 600,
        height: 25,
        content: 'telah menunjukkan prestasi cemerlang dalam menjayakan',
        fontSize: 15,
        fontFamily: 'serif',
        color: '#451a03',
        textAlign: 'center',
      },
      {
        id: 'program-placeholder',
        type: 'placeholder',
        x: 561,
        y: 445,
        width: 700,
        height: 40,
        placeholderType: 'program',
        fontSize: 24,
        fontFamily: 'Playfair Display, serif',
        fontWeight: 'bold',
        color: '#78350f',
        textAlign: 'center',
      },
      {
        id: 'sig-left-line',
        type: 'shape',
        shapeType: 'line',
        x: 270,
        y: 630,
        width: 220,
        height: 2,
        fill: '#78350f',
      },
      {
        id: 'sig-left-name',
        type: 'text',
        x: 270,
        y: 655,
        width: 240,
        height: 25,
        content: 'PENGETUA / GURU BESAR',
        fontSize: 13,
        fontFamily: 'sans-serif',
        fontWeight: 'bold',
        color: '#451a03',
        textAlign: 'center',
      },
      {
        id: 'date-placeholder',
        type: 'placeholder',
        x: 561,
        y: 645,
        width: 180,
        height: 25,
        placeholderType: 'date',
        fontSize: 13,
        fontFamily: 'sans-serif',
        color: '#78350f',
        textAlign: 'center',
      },
      {
        id: 'sig-right-line',
        type: 'shape',
        shapeType: 'line',
        x: 853,
        y: 630,
        width: 220,
        height: 2,
        fill: '#78350f',
      },
      {
        id: 'sig-right-name',
        type: 'text',
        x: 853,
        y: 655,
        width: 240,
        height: 25,
        content: 'YDP PIBG / PENGERUSI',
        fontSize: 13,
        fontFamily: 'sans-serif',
        fontWeight: 'bold',
        color: '#451a03',
        textAlign: 'center',
      },
    ],
  },
  {
    id: 'modern-training',
    name: 'Kursus & Bengkel (Modern Training)',
    description: 'Sijil latihan & CPD profesional dengan aksen warna hijau emerald dan kod QR.',
    category: 'training',
    width: 1123,
    height: 794,
    backgroundColor: '#f8fafc',
    elements: [
      {
        id: 'left-border-accent',
        type: 'shape',
        shapeType: 'rectangle',
        x: 15,
        y: 397,
        width: 14,
        height: 794,
        fill: '#059669',
      },
      {
        id: 'training-badge',
        type: 'icon',
        iconName: 'Trophy',
        x: 120,
        y: 110,
        width: 48,
        height: 48,
        stroke: '#059669',
        strokeWidth: 2,
      },
      {
        id: 'training-header',
        type: 'text',
        x: 400,
        y: 95,
        width: 500,
        height: 30,
        content: 'PUSAT LATIHAN & KEMAHIRAN',
        fontSize: 14,
        fontFamily: 'Poppins, sans-serif',
        fontWeight: 'bold',
        color: '#059669',
        textAlign: 'left',
        letterSpacing: 2,
      },
      {
        id: 'training-title',
        type: 'text',
        x: 400,
        y: 135,
        width: 500,
        height: 40,
        content: 'SIJIL TAMAT KURSUS',
        fontSize: 32,
        fontFamily: 'Poppins, sans-serif',
        fontWeight: 'bold',
        color: '#0f172a',
        textAlign: 'left',
      },
      {
        id: 'training-certifies',
        type: 'text',
        x: 561,
        y: 220,
        width: 600,
        height: 25,
        content: 'Adalah diperakui bahawa penama di bawah telah menyempurnakan kursus latihan:',
        fontSize: 15,
        fontFamily: 'sans-serif',
        color: '#475569',
        textAlign: 'center',
      },
      {
        id: 'name-placeholder',
        type: 'placeholder',
        x: 561,
        y: 285,
        width: 750,
        height: 60,
        placeholderType: 'name',
        fontSize: 42,
        fontFamily: 'Poppins, sans-serif',
        fontWeight: 'bold',
        color: '#047857',
        textAlign: 'center',
      },
      {
        id: 'program-placeholder',
        type: 'placeholder',
        x: 561,
        y: 380,
        width: 750,
        height: 50,
        placeholderType: 'program',
        fontSize: 26,
        fontFamily: 'Poppins, sans-serif',
        fontWeight: 'bold',
        color: '#0f172a',
        textAlign: 'center',
      },
      {
        id: 'qr-card',
        type: 'qr',
        x: 200,
        y: 610,
        width: 85,
        height: 85,
        qrData: '{VERIFY_URL}',
        color: '#047857',
      },
      {
        id: 'qr-text',
        type: 'text',
        x: 200,
        y: 675,
        width: 150,
        height: 20,
        content: 'Imbas untuk Semakan',
        fontSize: 10,
        fontFamily: 'sans-serif',
        color: '#64748b',
        textAlign: 'center',
      },
      {
        id: 'date-placeholder',
        type: 'placeholder',
        x: 561,
        y: 620,
        width: 200,
        height: 25,
        placeholderType: 'date',
        fontSize: 14,
        fontFamily: 'sans-serif',
        color: '#475569',
        textAlign: 'center',
      },
      {
        id: 'sig-trainer-line',
        type: 'shape',
        shapeType: 'line',
        x: 880,
        y: 610,
        width: 220,
        height: 2,
        fill: '#059669',
      },
      {
        id: 'sig-trainer-name',
        type: 'text',
        x: 880,
        y: 635,
        width: 240,
        height: 25,
        content: 'KETUA JURULATIH / INSTRUKTOR',
        fontSize: 13,
        fontFamily: 'Poppins, sans-serif',
        fontWeight: 'bold',
        color: '#0f172a',
        textAlign: 'center',
      },
    ],
  },
  {
    id: 'luxury-dark',
    name: 'Elegan Gelap (Luxury Dark)',
    description: 'Tema gelap obsidian berprestij dengan tipografi emas & bingkai mewah.',
    category: 'event',
    width: 1123,
    height: 794,
    backgroundColor: '#18181b',
    elements: [
      {
        id: 'gold-border',
        type: 'shape',
        shapeType: 'rectangle',
        x: 561,
        y: 397,
        width: 1040,
        height: 710,
        fill: 'transparent',
        stroke: '#eab308',
        strokeWidth: 2,
      },
      {
        id: 'star-icon',
        type: 'icon',
        iconName: 'Star',
        x: 561,
        y: 90,
        width: 44,
        height: 44,
        stroke: '#eab308',
        strokeWidth: 2,
      },
      {
        id: 'lux-title',
        type: 'text',
        x: 561,
        y: 155,
        width: 650,
        height: 45,
        content: 'CERTIFICATE OF EXCELLENCE',
        fontSize: 34,
        fontFamily: 'Playfair Display, serif',
        fontWeight: 'bold',
        color: '#eab308',
        textAlign: 'center',
        letterSpacing: 4,
      },
      {
        id: 'lux-sub',
        type: 'text',
        x: 561,
        y: 205,
        width: 400,
        height: 25,
        content: 'THIS CERTIFICATE IS PROUDLY AWARDED TO',
        fontSize: 12,
        fontFamily: 'sans-serif',
        color: '#a1a1aa',
        textAlign: 'center',
        letterSpacing: 2,
      },
      {
        id: 'name-placeholder',
        type: 'placeholder',
        x: 561,
        y: 285,
        width: 750,
        height: 70,
        placeholderType: 'name',
        fontSize: 50,
        fontFamily: 'Great Vibes, cursive',
        color: '#fef08a',
        textAlign: 'center',
      },
      {
        id: 'lux-desc',
        type: 'text',
        x: 561,
        y: 360,
        width: 600,
        height: 25,
        content: 'for extraordinary dedication, leadership and achievement in',
        fontSize: 15,
        fontFamily: 'serif',
        fontStyle: 'italic',
        color: '#a1a1aa',
        textAlign: 'center',
      },
      {
        id: 'program-placeholder',
        type: 'placeholder',
        x: 561,
        y: 420,
        width: 700,
        height: 45,
        placeholderType: 'program',
        fontSize: 26,
        fontFamily: 'Playfair Display, serif',
        fontWeight: 'bold',
        color: '#ffffff',
        textAlign: 'center',
      },
      {
        id: 'date-placeholder',
        type: 'placeholder',
        x: 270,
        y: 630,
        width: 200,
        height: 25,
        placeholderType: 'date',
        fontSize: 13,
        fontFamily: 'sans-serif',
        color: '#a1a1aa',
        textAlign: 'center',
      },
      {
        id: 'sig-gold-line',
        type: 'shape',
        shapeType: 'line',
        x: 853,
        y: 615,
        width: 220,
        height: 2,
        fill: '#eab308',
      },
      {
        id: 'sig-gold-title',
        type: 'text',
        x: 853,
        y: 640,
        width: 240,
        height: 25,
        content: 'PRESIDENT & CEO',
        fontSize: 13,
        fontFamily: 'Playfair Display, serif',
        fontWeight: 'bold',
        color: '#eab308',
        textAlign: 'center',
      },
    ],
  },
];

export function getPresetById(id: string): CertificatePreset | undefined {
  return CERTIFICATE_PRESETS.find((p) => p.id === id);
}
